"""Constants to minimize """
from constant import *

# physical model limit adjustments
# PHY_WATER_A_NDVI_LOWER_LIMIT = 0
# PHY_WATER_A_NDVI_UPPER_LIMIT = 0.1
PHY_WATER_A_NIR_UPPER_LIMIT = 0.01
# PHY_WATER_B_NDVI_UPPER_LIMIT = 0.01
PHY_WATER_B_NIR_UPPER_LIMIT = 0.018
# PHY_WATER_USE_NDMI = True
# PHY_WATER_A_NDMI_UPPER_LIMIT = 0.2
# PHY_WATER_B_NDMI_UPPER_LIMIT = 0.3

# water
# PHY_WATER_A_NIR_UPPER_LIMIT = 0.05
# PHY_WATER_B_NIR_UPPER_LIMIT = 0.08

# water_2
# PHY_WATER_A_NIR_UPPER_LIMIT = 0.015
# PHY_WATER_B_NIR_UPPER_LIMIT = 0.025

# water_3
# PHY_WATER_A_NIR_UPPER_LIMIT = 0.01
# PHY_WATER_B_NIR_UPPER_LIMIT = 0.018

# water_4
# PHY_WATER_USE_NDMI = True
# PHY_WATER_A_NDMI_UPPER_LIMIT = 0.05
# PHY_WATER_B_NDMI_UPPER_LIMIT = 0.11
